# Generated by Django 4.1.3 on 2022-11-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_comment_com_com_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
